### ISSUE TITLE
Issue with graph-pdf command

### ISSUE THREAD

**Issue by kohled** [BasilPH/vizel#12]
Hello! Thank you so much for sharing this very useful program. I'm running into an issue with graph-pdf command. I've included the error message from terminal below. I'm using The Archive. As I'm a CLI neophyte, most likely this is user error. Could you please advise? Thank you for your fine work.

> $ python3 --version
Python 3.7.7
$ vizel graph-pdf /Users/kohl/Dropbox/zettelkasten/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/graphviz/backend.py", line 159, in run
    proc = subprocess.Popen(cmd, startupinfo=get_startupinfo(), **kwargs)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'dot': 'dot'

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "/usr/local/bin/vizel", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/vizel/cli.py", line 110, in graph_pdf
    dot.render(pdf_name, cleanup=True)
  File "/usr/local/lib/python3.7/site-packages/graphviz/files.py", line 209, in render
    quiet=quiet)
  File "/usr/local/lib/python3.7/site-packages/graphviz/backend.py", line 206, in render
    run(cmd, capture_output=True, cwd=cwd, check=True, quiet=quiet)
  File "/usr/local/lib/python3.7/site-packages/graphviz/backend.py", line 162, in run
    raise ExecutableNotFound(cmd)
graphviz.backend.ExecutableNotFound: failed to execute ['dot', '-Tpdf', '-O', 'vizel_graph'], make sure the Graphviz executables are on your systems' PATH

**Comment by BasilPH** [comment]
Hey @kohled, thanks for giving vizel a try and reaching out. It looks like you're on a mac. You need to install graphviz on the system as well. The easiest way to do this is with `brew install graphviz`.

I'll add this to the documentation.

Do the other commands work?

**Comment by kohled** [comment]
Dang. Thought I'd checked that graphviz was installed. Thanks for the help.

Putting this fine program to immediate daily use. Really appreciate your work.
